server.port: 8082
spring:
  application.name: auth
  datasource:
    password: admin123
    username: admin
    url: jdbc:postgresql://localhost:5432/auth
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    database: PostgreSQL
  sql:
    init:
      platform: PostgreSQL
server:
  error:
    include-message: always
logging.level.org.springframework.security: TRACE
token:
  refreshTokenExpirationMs: '604800000'
  accessTokenExpirationMs: '86400000'
  refreshTokenCookieName: jwt
  secretKey: 5267556B58703273357638792F423F4528482B4D6251655368566D5971337436
feign:
  user:
    url: http://localhost:8081
